spring:
  application:
    name: PickMeal

  # Database 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # 비동기 스레드 풀 설정
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
      thread-name-prefix: diet-async-

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-mini
          temperature: 1.0

# Swagger (OpenAPI) 설정
springdoc:
  swagger-ui:
    operations-sorter: alpha
  api-docs:
    path: /api-docs

# JWT 및 커스텀 보안 설정
jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-expiration: 1800000 # 30분
  refresh-expiration: 1209600000 # 14일

# 공공 데이터 포털 api
external:
  recipe:
    public-data:
      base-url: http://211.237.50.150:7080/openapi
      api-key: ${PUBLIC_DATA_API_KEY:sample}
      type: json
      recipe-info-api-url: Grid_20150827000000000226_1
      recipe-ingredient-api-url: Grid_20150827000000000227_1

    food-safety:
      base-url: http://openapi.foodsafetykorea.go.kr/api/
      api-key: ${FOOD_SAFETY_API_KEY:sample}
      service-id: COOKRCP01
      type: json


# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

debug: true

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

cookie:
  secure: ${COOKIE_SECURE:false}